# Generated by Django 3.2.6 on 2021-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userelementrydata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
