# Generated by Django 3.2.6 on 2021-09-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userelementrydata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_requests', models.IntegerField(default=1)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userelementrydata')),
            ],
        ),
    ]
